### ISSUE TITLE
Failable Initializer?

### ISSUE THREAD

**Issue by cjwirth** [qutheory/fluent#11]
I was thinking it might be nice if the initializer was failable, or maybe throwable. 

I know it's probably a rare case, but it's possible that you could get passed some invalid data. With the current implementation, the only thing we can do is come up with default values for it. That might not be the worst thing in the world -- most times the initializer will be called is when there is an actual record in the database, so something needs to be done!

Just a thought :smile:

**Comment by tannernelson** [comment]
That's a good idea. I'll keep this open as a reminder to add it.

**Comment by tannernelson** [comment]
This has been added.
