### ISSUE TITLE
Ability to get item ID after save

### ISSUE THREAD

**Issue by cjwirth** [qutheory/fluent#12]
I'm making a very basic API with the basic `ResourceController` using vapor.

Since there is already an `id` on the `Model` protocol, which is "nil when not saved yet", it would be cool if there was some way to get the `id` after saving.

Maybe `save` could populate the `id` field, or return an `id`, or maybe return a newly instantiated model with the `id` filled in. 

That way, when a user makes a POST request, they can actually know the ID of the object to fetch it again.

**Comment by tannernelson** [comment]
Great idea.

**Comment by AnthonyMDev** [comment]
👍

**Comment by tannernelson** [comment]
This has been implemented
