### ISSUE TITLE
`Model.id` has an inconsistent type

### ISSUE THREAD

**Issue by sdbip** [qutheory/fluent#13]
```swift
protocol Model { var id: String? { get } }
```
vs
```swift
extension Model { func find(id: Int) -> Self }
```

**Comment by tannernelson** [comment]
Good point. The Model id is a String in case any database implementations might use a UUID or something for the model identifiers. Not quite sure how NoSQL does it. If everyone uses integers, then we can change this.

**Comment by ketzusaka** [comment]
I use strings sometimes. Might be a good case for a generic?

**Comment by alomvar** [comment]
MongoDB document ids ([ObjectId](https://docs.mongodb.org/manual/reference/method/ObjectId/)) are often represented as string (even though they actually are a 12 Byte BSON type).

**Comment by Joannis** [comment]
We (like any MongoDB driver) accept ObjectID as a hex-string and usually represent it as such in `MongoKitten`.

**Comment by tannernelson** [comment]
Possibly `id` should be of type `Fluent.Value` so we can store an integer, string, or raw byte array. A regular `String` would also probably work fine.

**Comment by AnthonyMDev** [comment]
Seems like this is a good case for using `associated type` on the `Model` protocol. The user should be able to make their primary key any type that conforms to `Equatable` and can be mapped to a DB column in my opinion.

**Comment by Evertt** [comment]
@AnthonyMDev my issue with `associatedType` is that then we can't use `Model` as a generic requirement anymore. Which would be a pity, since I would like to, as some point, build an `EntityManager` class which manages entities like Doctrine does it. And for that it would be very nice to be able to have an array of `Model`s without specifying which models I'm working with.

**Comment by AnthonyMDev** [comment]
@Evertt Got it. That makes sense. I'll continue to this about this issue. If I come up with any other proposed solutions I'll let you know.

**Comment by tannernelson** [comment]
This will be changed to `Value`
