### ISSUE TITLE
Model associations?

### ISSUE THREAD

**Issue by MoridinBG** [qutheory/fluent#24]
Are there any plans/ideas about having associations between models? Maybe like has_many, belongs_to, etc?
I can start working on this with some guidance on how do we want it to look like.

**Comment by MoridinBG** [comment]
My initial sketch is for a family of generic classes that manage the db, such as HasManyHasManyAssociation, BelongsToAssociation, that you add as private properties to your Model implementation and corresponding public properties exposing the models returned by the associations

    class Post: Model {
        // Model implementation - id, init, etc

        private let authorAssociation = BelongsToAssociation(User, via: "author_id")
        var author: User {
            get {
                return authorAssociation.model
            }
            set {
                authorAssociation.model = newValue
            }
        }
    }

**Comment by tannernelson** [comment]
Yes we definitely want to include those types of relations at some point. Though I think that's farther down on the roadmap than we currently are. I'd like to have working SQL _and_ MongoDB support for the basic features (creating, reading, destroying db models, etc) before we move into more advanced features.

**Comment by tannernelson** [comment]
This is on the roadmap now.
