### ISSUE TITLE
Vulnerable to SQL injection

### ISSUE THREAD

**Issue by C0deH4cker** [qutheory/fluent#5]
This database framework is vulnerable to SQL injection. I have created an example project showing this behavior [here](https://github.com/C0deH4cker/FluentSQLi). You unfortunately can't build SQL statements with normal string manipulations. Instead, each SQL statement must be complete, with possible parameters. This is known as parameterized queries. For SQLite, [this](http://www.askyb.com/cpp/c-sqlite-example-with-parameterized-query/) is a good resource to understand how they work, using `sqlite3_prepare()`.

The impact of this is that any user can control the contents of the SQL statements being executed, which can allow them to dump databases, modify data, log in without a password, or drop tables.

**Comment by tannernelson** [comment]
Yes, this one is on the todo list. Should be implemented in the SQLite Driver repo.

**Comment by C0deH4cker** [comment]
The main problem seems to be [the SQL class](https://github.com/tannernelson/fluent/blob/master/Sources/SQL.swift), which I don't believe should exist. The syntax between different implementations of SQL databases is different, so there shouldn't be a common SQL statement builder class. It could instead hold information such as what type of query to perform, what table and column names, and what parameters to use, and hand this generic data structure to a specialized SQL class for each implementation (MySQL, PostgreSQL, SQLite, etc), which has pre-built queries and picks which one to use based on the data in this structure. If I have time, I'll submit a pull request.

**Comment by tannernelson** [comment]
> The syntax between different implementations of SQL databases is different, so there shouldn't be a common SQL statement builder class.

There are enough similarities between MySQL, PostgreSQL, and SQLite to merit a shared `SQL` class. It was my intention to subclass `SQL` in the individual drivers (MySQL, etc) if there was some query syntax specific to that database. 

> It could instead hold information such as what type of query to perform, what table and column names, and what parameters to use, and hand this generic data structure

The `Query` class is what you are describing. It stores all of this information generically.

**Comment by C0deH4cker** [comment]
Even if the normal SQL syntax is the same, each implementation uses a different parameterization format. Yeah, this will lead to some code duplication within each of the SQL classes per dialect, but I feel it would be worth it to keep the SQL code completely separate.

**Comment by tannernelson** [comment]
I believe it would be possible to achieve this by overriding methods in a subclass of `SQL` without duplicating any code. If you want to change how the parameterization works, override that method. That's the whole point of OOP. The vast majority of queries would be unaffected. For example, `SELECT * FROM users WHERE age >= 20 AND name LIKE 'Tanner';` works in almost every engine. 

 I will be adding these features soon, as well as fixing the SQL injection issue with the SQLite driver.

**Comment by tannernelson** [comment]
Thanks for the link to `askyb.com`. That looks like exactly what I need.

**Comment by artkay** [comment]
@C0deH4cker I feel like 

> some code duplication

should read

> 98% code duplication

In my life I was working with bunch of different SQL implementations (MSSQL, Sybase, MySQL, PostgreSQL etc.). At the end of the day they are all pretty much the same doing basic stuff. And I feel like this project first goal is to be able to do the basic stuff. When we get to stored procedures and triggers - then we would probably duplicate something.

Thanks for testing the project on such early stage.

**Comment by Lagawrd** [comment]
@C0deH4cker It's probably more future proof to have completely separate code for each SQL class, but I also think it's overkill especially since there are more similarities to retrieving and writing data between all SQL implementations than there are differences.  I don't see anything wrong with having a parent builder-like abstract class that all other SQL implementations extends and build on top of.

**Comment by C0deH4cker** [comment]
I should rephrase my suggestion. I suggest to absolutely reuse as much code as reasonably possible. In fact, the only code specific to each implementation I'm thinking of is the code interfacing with the specific SQL library (which is unavoidable), and a dictionary or probably enum(String) that holds the prepared SQL statements in each dialect including parameterization format. Then the base SQL class can still exist, but it won't contain any SQL code directly, as that would be referenced from each implementation's interface.

**Comment by tannernelson** [comment]
@C0deH4cker I agree. That will be the plan. I'm pretty sure all SQL engines include escaping functions as well, so that will not be included in the base class.

**Comment by C0deH4cker** [comment]
In general, it's best to avoid escaping functions such as `mysql_real_escape_string()` if you can instead use prepared SQL statements using parameterization. See [this StackOverflow post](http://stackoverflow.com/questions/5741187/sql-injection-that-gets-around-mysql-real-escape-string) for some real examples of attacks despite using `mysql_real_escape_string()`.

**Comment by tannernelson** [comment]
Good point. Does `mysql` come with something like SQLite's `sqlite3_prepare`?

**Comment by C0deH4cker** [comment]
Yes, every major SQL implementation has a way of making prepared statements. I'll look them up and list them when I get to my laptop.

**Comment by C0deH4cker** [comment]
Here's what I found for using prepared statements on three of the most popular SQL engines:

* SQLite: [`sqlite3_prepare_v2()`](https://www.sqlite.org/c3ref/prepare.html)
    * Look at section 5.0 on [this page](https://www.sqlite.org/cintro.html) for parameter syntax. [This code](https://icculus.org/~chunky/stuff/sqlite3_example/sqlite3_example_bind.c) shows a complete example including the code for binding parameters with functions like `sqlite3_bind_double()`.
* MySQL: [`mysql_stmt_prepare()`](https://dev.mysql.com/doc/refman/5.7/en/mysql-stmt-prepare.html)
    * Look at page 68 of [this PDF](http://www.kitebird.com/mysql-book/ch07-4ed.pdf) for an example. Basically, the syntax is just using `?` for each parameterized value, and then binding each parameter in a param array including setting the type.
* PostgreSQL: [`PQprepare()`](http://www.postgresql.org/docs/9.3/static/libpq-exec.html)
    * [This man page](http://libpqtypes.esilo.com/man3/PQparamExec.html) shows example usage of `PQparamExec()`, which is very similar to using `PQparamExecPrepared()` to execute a statement prepared via `PQprepare()` (which is what we probably want here).

**Comment by d-abe** [comment]
How about my implementation? (using template method design pattern)
https://github.com/d-abe/fluent

Each driver can override methods for using escape or prepared statements.
(And, it keeps compatibility of original `SQL` class)

I forked PostgreSQL driver and override for escaping.(I made `PostgreSQLDialect` class. But it's only for v9.x)
https://github.com/d-abe/fluent-postgresql

Same as above, if we want to use prepared statements,

```swift
    private var paramCount: Int = 0
    override public func getData(key: String) -> String {
        if let data = self.data {
            if let val = data[key] {
                if val == "NULL" {
                    return val
                } else {
                    paramCount = paramCount+1
                    return "$" + String(paramCount)
                }
            }
        }
        return ""
    }
```

and then, use `PQexecParams()` instead of `PQexec` in `PSQLStatement` class.

**Comment by tannernelson** [comment]
@d-abe Could you create a pull request with those changes?

**Comment by d-abe** [comment]
I added a little changes and make a PR. #14 

I'm sorry if I made a mistake to do that (because I don't know so much about GitHub PR rules...)
But please check it :)

**Comment by Prince2k3** [comment]
@C0deH4cker I think the new update takes care of the injection issue. You mind double checking this?
